name: On Push

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: check cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}

      - name: check cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}

      - name: check cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: build
        run: npm run build

      - name: upload build
        uses: actions/upload-artifact@2
        with:
          name: build
          path: dist/cookie-fox/

  test:
    runs-on: ubuntu-latest
    needs: install

    strategy:
      matrix:
        node: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}

      - name: check cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test -- --no-watch
