name: On Merge with Master

on:
  pull_request:
    branches: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}

      - name: check cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:coverage -- --no-watch

      - name: Upload coverage report to codecov.io
        run: bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_TOKEN}}

      - name: build
        run: npm run build -- --prod

      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/cookie-fox/

      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npx semantic-release
